[formatting]
    align_comments=true
    align_entries=false
    align_single_comments=false
    allowed_blank_lines=1
    array_auto_collapse=true
    array_auto_expand=true
    array_trailing_comma=true
    column_width=100
    compact_arrays=true
    compact_entries=true
    compact_inline_tables=true
    crlf=false
    indent_entries=true
    indent_string="    "
    indent_tables=true
    inline_table_expand=true
    reorder_arrays=true
    reorder_keys=true
    trailing_newline=true
